// Code generated by mockery v2.53.6. DO NOT EDIT.

package otp

import mock "github.com/stretchr/testify/mock"

// MockRandomReader is an autogenerated mock type for the RandomReader type
type MockRandomReader struct {
	mock.Mock
}

type MockRandomReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRandomReader) EXPECT() *MockRandomReader_Expecter {
	return &MockRandomReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: b
func (_m *MockRandomReader) Read(b []byte) (int, error) {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(b)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRandomReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockRandomReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *MockRandomReader_Expecter) Read(b interface{}) *MockRandomReader_Read_Call {
	return &MockRandomReader_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *MockRandomReader_Read_Call) Run(run func(b []byte)) *MockRandomReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockRandomReader_Read_Call) Return(n int, err error) *MockRandomReader_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRandomReader_Read_Call) RunAndReturn(run func([]byte) (int, error)) *MockRandomReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRandomReader creates a new instance of MockRandomReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRandomReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRandomReader {
	mock := &MockRandomReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
