// Code generated by mockery v2.53.6. DO NOT EDIT.

package cert

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDirWriter is an autogenerated mock type for the DirWriter type
type MockDirWriter struct {
	mock.Mock
}

type MockDirWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirWriter) EXPECT() *MockDirWriter_Expecter {
	return &MockDirWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: ctx, domain, certPEM, keyPEM
func (_m *MockDirWriter) Write(ctx context.Context, domain string, certPEM []byte, keyPEM []byte) error {
	ret := _m.Called(ctx, domain, certPEM, keyPEM)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) error); ok {
		r0 = rf(ctx, domain, certPEM, keyPEM)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDirWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockDirWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - certPEM []byte
//   - keyPEM []byte
func (_e *MockDirWriter_Expecter) Write(ctx interface{}, domain interface{}, certPEM interface{}, keyPEM interface{}) *MockDirWriter_Write_Call {
	return &MockDirWriter_Write_Call{Call: _e.mock.On("Write", ctx, domain, certPEM, keyPEM)}
}

func (_c *MockDirWriter_Write_Call) Run(run func(ctx context.Context, domain string, certPEM []byte, keyPEM []byte)) *MockDirWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].([]byte))
	})
	return _c
}

func (_c *MockDirWriter_Write_Call) Return(_a0 error) *MockDirWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDirWriter_Write_Call) RunAndReturn(run func(context.Context, string, []byte, []byte) error) *MockDirWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDirWriter creates a new instance of MockDirWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirWriter {
	mock := &MockDirWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
