// Code generated by mockery v2.53.6. DO NOT EDIT.

package cert

import (
	tls "crypto/tls"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockACMEManager is an autogenerated mock type for the ACMEManager type
type MockACMEManager struct {
	mock.Mock
}

type MockACMEManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockACMEManager) EXPECT() *MockACMEManager_Expecter {
	return &MockACMEManager_Expecter{mock: &_m.Mock}
}

// GetCertificate provides a mock function with given fields: hello
func (_m *MockACMEManager) GetCertificate(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
	ret := _m.Called(hello)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificate")
	}

	var r0 *tls.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(*tls.ClientHelloInfo) (*tls.Certificate, error)); ok {
		return rf(hello)
	}
	if rf, ok := ret.Get(0).(func(*tls.ClientHelloInfo) *tls.Certificate); ok {
		r0 = rf(hello)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(*tls.ClientHelloInfo) error); ok {
		r1 = rf(hello)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockACMEManager_GetCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificate'
type MockACMEManager_GetCertificate_Call struct {
	*mock.Call
}

// GetCertificate is a helper method to define mock.On call
//   - hello *tls.ClientHelloInfo
func (_e *MockACMEManager_Expecter) GetCertificate(hello interface{}) *MockACMEManager_GetCertificate_Call {
	return &MockACMEManager_GetCertificate_Call{Call: _e.mock.On("GetCertificate", hello)}
}

func (_c *MockACMEManager_GetCertificate_Call) Run(run func(hello *tls.ClientHelloInfo)) *MockACMEManager_GetCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*tls.ClientHelloInfo))
	})
	return _c
}

func (_c *MockACMEManager_GetCertificate_Call) Return(_a0 *tls.Certificate, _a1 error) *MockACMEManager_GetCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockACMEManager_GetCertificate_Call) RunAndReturn(run func(*tls.ClientHelloInfo) (*tls.Certificate, error)) *MockACMEManager_GetCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// HTTPHandler provides a mock function with given fields: fallback
func (_m *MockACMEManager) HTTPHandler(fallback http.Handler) http.Handler {
	ret := _m.Called(fallback)

	if len(ret) == 0 {
		panic("no return value specified for HTTPHandler")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(fallback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// MockACMEManager_HTTPHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPHandler'
type MockACMEManager_HTTPHandler_Call struct {
	*mock.Call
}

// HTTPHandler is a helper method to define mock.On call
//   - fallback http.Handler
func (_e *MockACMEManager_Expecter) HTTPHandler(fallback interface{}) *MockACMEManager_HTTPHandler_Call {
	return &MockACMEManager_HTTPHandler_Call{Call: _e.mock.On("HTTPHandler", fallback)}
}

func (_c *MockACMEManager_HTTPHandler_Call) Run(run func(fallback http.Handler)) *MockACMEManager_HTTPHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *MockACMEManager_HTTPHandler_Call) Return(_a0 http.Handler) *MockACMEManager_HTTPHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockACMEManager_HTTPHandler_Call) RunAndReturn(run func(http.Handler) http.Handler) *MockACMEManager_HTTPHandler_Call {
	_c.Call.Return(run)
	return _c
}

// TLSConfig provides a mock function with no fields
func (_m *MockACMEManager) TLSConfig() *tls.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TLSConfig")
	}

	var r0 *tls.Config
	if rf, ok := ret.Get(0).(func() *tls.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Config)
		}
	}

	return r0
}

// MockACMEManager_TLSConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSConfig'
type MockACMEManager_TLSConfig_Call struct {
	*mock.Call
}

// TLSConfig is a helper method to define mock.On call
func (_e *MockACMEManager_Expecter) TLSConfig() *MockACMEManager_TLSConfig_Call {
	return &MockACMEManager_TLSConfig_Call{Call: _e.mock.On("TLSConfig")}
}

func (_c *MockACMEManager_TLSConfig_Call) Run(run func()) *MockACMEManager_TLSConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockACMEManager_TLSConfig_Call) Return(_a0 *tls.Config) *MockACMEManager_TLSConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockACMEManager_TLSConfig_Call) RunAndReturn(run func() *tls.Config) *MockACMEManager_TLSConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockACMEManager creates a new instance of MockACMEManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockACMEManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockACMEManager {
	mock := &MockACMEManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
