// Code generated by mockery v2.53.6. DO NOT EDIT.

package file

import (
	io "io"
	fs "io/fs"

	os "os"

	mock "github.com/stretchr/testify/mock"
)

// MockFS is an autogenerated mock type for the FS type
type MockFS struct {
	mock.Mock
}

type MockFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFS) EXPECT() *MockFS_Expecter {
	return &MockFS_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function with given fields: dst, src
func (_m *MockFS) Copy(dst io.Writer, src io.Reader) (int64, error) {
	ret := _m.Called(dst, src)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Writer, io.Reader) (int64, error)); ok {
		return rf(dst, src)
	}
	if rf, ok := ret.Get(0).(func(io.Writer, io.Reader) int64); ok {
		r0 = rf(dst, src)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(io.Writer, io.Reader) error); ok {
		r1 = rf(dst, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFS_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockFS_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - dst io.Writer
//   - src io.Reader
func (_e *MockFS_Expecter) Copy(dst interface{}, src interface{}) *MockFS_Copy_Call {
	return &MockFS_Copy_Call{Call: _e.mock.On("Copy", dst, src)}
}

func (_c *MockFS_Copy_Call) Run(run func(dst io.Writer, src io.Reader)) *MockFS_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockFS_Copy_Call) Return(written int64, err error) *MockFS_Copy_Call {
	_c.Call.Return(written, err)
	return _c
}

func (_c *MockFS_Copy_Call) RunAndReturn(run func(io.Writer, io.Reader) (int64, error)) *MockFS_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: name
func (_m *MockFS) Create(name string) (*os.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFS_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFS_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *MockFS_Expecter) Create(name interface{}) *MockFS_Create_Call {
	return &MockFS_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *MockFS_Create_Call) Run(run func(name string)) *MockFS_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFS_Create_Call) Return(_a0 *os.File, _a1 error) *MockFS_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFS_Create_Call) RunAndReturn(run func(string) (*os.File, error)) *MockFS_Create_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function with given fields: path, perm
func (_m *MockFS) MkdirAll(path string, perm fs.FileMode) error {
	ret := _m.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = rf(path, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFS_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFS_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *MockFS_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFS_MkdirAll_Call {
	return &MockFS_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFS_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *MockFS_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.FileMode))
	})
	return _c
}

func (_c *MockFS_MkdirAll_Call) Return(_a0 error) *MockFS_MkdirAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFS_MkdirAll_Call) RunAndReturn(run func(string, fs.FileMode) error) *MockFS_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: name
func (_m *MockFS) Open(name string) (*os.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockFS_Expecter) Open(name interface{}) *MockFS_Open_Call {
	return &MockFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockFS_Open_Call) Run(run func(name string)) *MockFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFS_Open_Call) Return(_a0 *os.File, _a1 error) *MockFS_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFS_Open_Call) RunAndReturn(run func(string) (*os.File, error)) *MockFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function with given fields: name, flag, perm
func (_m *MockFS) OpenFile(name string, flag int, perm fs.FileMode) (*os.File, error) {
	ret := _m.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, fs.FileMode) (*os.File, error)); ok {
		return rf(name, flag, perm)
	}
	if rf, ok := ret.Get(0).(func(string, int, fs.FileMode) *os.File); ok {
		r0 = rf(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, fs.FileMode) error); ok {
		r1 = rf(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFS_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type MockFS_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm fs.FileMode
func (_e *MockFS_Expecter) OpenFile(name interface{}, flag interface{}, perm interface{}) *MockFS_OpenFile_Call {
	return &MockFS_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *MockFS_OpenFile_Call) Run(run func(name string, flag int, perm fs.FileMode)) *MockFS_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *MockFS_OpenFile_Call) Return(_a0 *os.File, _a1 error) *MockFS_OpenFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFS_OpenFile_Call) RunAndReturn(run func(string, int, fs.FileMode) (*os.File, error)) *MockFS_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *MockFS) Stat(name string) (fs.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFS_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFS_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockFS_Expecter) Stat(name interface{}) *MockFS_Stat_Call {
	return &MockFS_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockFS_Stat_Call) Run(run func(name string)) *MockFS_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFS_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *MockFS_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFS_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *MockFS_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFS creates a new instance of MockFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFS {
	mock := &MockFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
