// Code generated by mockery v2.53.6. DO NOT EDIT.

package random

import (
	big "math/big"

	mock "github.com/stretchr/testify/mock"
)

// MockCryptoSource is an autogenerated mock type for the CryptoSource type
type MockCryptoSource struct {
	mock.Mock
}

type MockCryptoSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCryptoSource) EXPECT() *MockCryptoSource_Expecter {
	return &MockCryptoSource_Expecter{mock: &_m.Mock}
}

// Int provides a mock function with given fields: max
func (_m *MockCryptoSource) Int(max *big.Int) (*big.Int, error) {
	ret := _m.Called(max)

	if len(ret) == 0 {
		panic("no return value specified for Int")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*big.Int) (*big.Int, error)); ok {
		return rf(max)
	}
	if rf, ok := ret.Get(0).(func(*big.Int) *big.Int); ok {
		r0 = rf(max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*big.Int) error); ok {
		r1 = rf(max)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoSource_Int_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Int'
type MockCryptoSource_Int_Call struct {
	*mock.Call
}

// Int is a helper method to define mock.On call
//   - max *big.Int
func (_e *MockCryptoSource_Expecter) Int(max interface{}) *MockCryptoSource_Int_Call {
	return &MockCryptoSource_Int_Call{Call: _e.mock.On("Int", max)}
}

func (_c *MockCryptoSource_Int_Call) Run(run func(max *big.Int)) *MockCryptoSource_Int_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*big.Int))
	})
	return _c
}

func (_c *MockCryptoSource_Int_Call) Return(n *big.Int, err error) *MockCryptoSource_Int_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCryptoSource_Int_Call) RunAndReturn(run func(*big.Int) (*big.Int, error)) *MockCryptoSource_Int_Call {
	_c.Call.Return(run)
	return _c
}

// Prime provides a mock function with given fields: bits
func (_m *MockCryptoSource) Prime(bits int) (*big.Int, error) {
	ret := _m.Called(bits)

	if len(ret) == 0 {
		panic("no return value specified for Prime")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*big.Int, error)); ok {
		return rf(bits)
	}
	if rf, ok := ret.Get(0).(func(int) *big.Int); ok {
		r0 = rf(bits)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(bits)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoSource_Prime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prime'
type MockCryptoSource_Prime_Call struct {
	*mock.Call
}

// Prime is a helper method to define mock.On call
//   - bits int
func (_e *MockCryptoSource_Expecter) Prime(bits interface{}) *MockCryptoSource_Prime_Call {
	return &MockCryptoSource_Prime_Call{Call: _e.mock.On("Prime", bits)}
}

func (_c *MockCryptoSource_Prime_Call) Run(run func(bits int)) *MockCryptoSource_Prime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCryptoSource_Prime_Call) Return(p *big.Int, err error) *MockCryptoSource_Prime_Call {
	_c.Call.Return(p, err)
	return _c
}

func (_c *MockCryptoSource_Prime_Call) RunAndReturn(run func(int) (*big.Int, error)) *MockCryptoSource_Prime_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: b
func (_m *MockCryptoSource) Read(b []byte) (int, error) {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(b)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoSource_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockCryptoSource_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *MockCryptoSource_Expecter) Read(b interface{}) *MockCryptoSource_Read_Call {
	return &MockCryptoSource_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *MockCryptoSource_Read_Call) Run(run func(b []byte)) *MockCryptoSource_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockCryptoSource_Read_Call) Return(n int, err error) *MockCryptoSource_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCryptoSource_Read_Call) RunAndReturn(run func([]byte) (int, error)) *MockCryptoSource_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCryptoSource creates a new instance of MockCryptoSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCryptoSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCryptoSource {
	mock := &MockCryptoSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
