// Code generated by mockery v2.53.6. DO NOT EDIT.

package ip

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// MockAddrLookup is an autogenerated mock type for the AddrLookup type
type MockAddrLookup struct {
	mock.Mock
}

type MockAddrLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddrLookup) EXPECT() *MockAddrLookup_Expecter {
	return &MockAddrLookup_Expecter{mock: &_m.Mock}
}

// InterfaceAddrs provides a mock function with no fields
func (_m *MockAddrLookup) InterfaceAddrs() ([]net.Addr, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InterfaceAddrs")
	}

	var r0 []net.Addr
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]net.Addr, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Addr)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddrLookup_InterfaceAddrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterfaceAddrs'
type MockAddrLookup_InterfaceAddrs_Call struct {
	*mock.Call
}

// InterfaceAddrs is a helper method to define mock.On call
func (_e *MockAddrLookup_Expecter) InterfaceAddrs() *MockAddrLookup_InterfaceAddrs_Call {
	return &MockAddrLookup_InterfaceAddrs_Call{Call: _e.mock.On("InterfaceAddrs")}
}

func (_c *MockAddrLookup_InterfaceAddrs_Call) Run(run func()) *MockAddrLookup_InterfaceAddrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAddrLookup_InterfaceAddrs_Call) Return(_a0 []net.Addr, _a1 error) *MockAddrLookup_InterfaceAddrs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddrLookup_InterfaceAddrs_Call) RunAndReturn(run func() ([]net.Addr, error)) *MockAddrLookup_InterfaceAddrs_Call {
	_c.Call.Return(run)
	return _c
}

// Interfaces provides a mock function with no fields
func (_m *MockAddrLookup) Interfaces() ([]net.Interface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interfaces")
	}

	var r0 []net.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]net.Interface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []net.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddrLookup_Interfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Interfaces'
type MockAddrLookup_Interfaces_Call struct {
	*mock.Call
}

// Interfaces is a helper method to define mock.On call
func (_e *MockAddrLookup_Expecter) Interfaces() *MockAddrLookup_Interfaces_Call {
	return &MockAddrLookup_Interfaces_Call{Call: _e.mock.On("Interfaces")}
}

func (_c *MockAddrLookup_Interfaces_Call) Run(run func()) *MockAddrLookup_Interfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAddrLookup_Interfaces_Call) Return(_a0 []net.Interface, _a1 error) *MockAddrLookup_Interfaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddrLookup_Interfaces_Call) RunAndReturn(run func() ([]net.Interface, error)) *MockAddrLookup_Interfaces_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAddrLookup creates a new instance of MockAddrLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddrLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddrLookup {
	mock := &MockAddrLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
